### ISSUE TITLE
I would like to have more detailed examples of file structures during the upload process!

### ISSUE THREAD

**Issue by WeiMengXS** [PacoVK/tapir#364]
When uploading the provider, we already know that we need to prepare the .zip file containing all the files described in the '[how to prepare release](https://developer.hashicorp.com/terraform/registry/providers/publishing#preparing-your-provider)' documentation. However, when uploading the module, it seems that the documentation does not explicitly specify how the directory structure should be maintained for the upload. I tried uploading the downloaded module and encountered the following error.
1、
error:
<img width="1727" alt="image" src="https://github.com/PacoVK/tapir/assets/54929266/7831d743-3057-4fc5-a8a3-f9c364df841d">

My directory structure is:
<img width="1006" alt="image" src="https://github.com/PacoVK/tapir/assets/54929266/8547cd33-cfa3-4965-b577-e6c7a7b11ee6">

command use:
`curl -XPOST  -H 'x-api-key:eNsZxQ1vQsY0QqEGgWMHXsKE' --fail-with-body -F archive=@terraform-aws-iam-0.0.2.zip "https://example.com/terraform/modules/v1/fc/vpc/aws/0.0.2"`

2、
error:
<img width="1727" alt="image" src="https://github.com/PacoVK/tapir/assets/54929266/54a0333e-ed29-4126-a505-bfd799462727">

My directory structure is:
<img width="619" alt="image" src="https://github.com/PacoVK/tapir/assets/54929266/95263efb-abf3-408c-aa7e-8f7721c9c852">

command use:
`curl -XPOST  -H 'x-api-key:eNsZxQ1vQsY0QqEGgWMHXsKE' --fail-with-body -F archive=@Archiv.zip "https://example.com/terraform/modules/v1/fc/vpc/aws/0.0.2"`

**Comment by PacoVK** [comment]
Hey, indeed Tapir was not able to handle nested modules properly. I addressed this in #365 and also added now more details for the expected module structure (althought, the recommended layout is a **should**) However, the .tf files should be at the root level within the .zip file :) [see](https://github.com/PacoVK/tapir#upload-a-module)
Before i create another release you can already check using the Docker image `pacovk/tapir:main` or `pacovk/tapir:latest`

**Comment by WeiMengXS** [comment]
hi,When I upload the module, the problem still occurs, but there is no problem uploading the provider.
<img width="410" alt="image" src="https://github.com/PacoVK/tapir/assets/54929266/f5e6da6f-5e1c-4925-8b8f-54a0e136d591">

command use:
`curl -XPOST  -H 'x-api-key:xxxxx' --fail-with-body -F archive=@Archiv.zip "https://xxx.com/terraform/modules/v1/fc/vpc/aws/0.0.2"`

Encounter problems:
<img width="1716" alt="image" src="https://github.com/PacoVK/tapir/assets/54929266/34dcafda-7582-467d-b5f3-0efb2ceaeb2b">

What's the problem here? es seems to work.
What aspects should I investigate?

**Comment by PacoVK** [comment]
While the logs indicate everything worked well, there is an issue with the report index mapping in ES. So you can either 
* try to start with a fresh Elasticsearch
* delete and recreate (recreate can Tapir handle for you) the reports index

**Comment by WeiMengXS** [comment]
<img width="1722" alt="image" src="https://github.com/PacoVK/tapir/assets/54929266/bf223839-51c9-4f1a-a3b7-de6d192b1178">

I checked the index and it is normal.
<img width="988" alt="image" src="https://github.com/PacoVK/tapir/assets/54929266/bed7467c-ff0c-4e9d-8de4-42f2822ba68b">

Files I uploaded：
[Archiv.zip](https://github.com/PacoVK/tapir/files/13808853/Archiv.zip)

**Comment by PacoVK** [comment]
Thanks, again! Fix i on the way

**Comment by WeiMengXS** [comment]
When using module here, it seems to point to s3, and I chose local storage.

<img width="1624" alt="image" src="https://github.com/PacoVK/tapir/assets/54929266/b08383b0-5d94-4992-a93e-f71c5d7d176d">

**Comment by PacoVK** [comment]
I think there was a leftover from a bigger refactoring, i fixed it and it will be available in latest soon. A release will also follow soonish! Thanks again, i use Tapir with s3 hence i did not recognize this faux pas

**Comment by WeiMengXS** [comment]
Thank you very much, the module management problem has been solved.
